apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ntjvjsp5s-python 
  janus-idp.io/tekton: ntjvjsp5s-python
  backstage.io/kubernetes-id: ntjvjsp5s-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ntjvjsp5s-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml